# Function that generates output in the tidy format
# from run.jags output
STOCfree_tidy_output <- function(STOCfree_model_output){

  samples <- STOCfree_model_output$mcmc

  ## tidying the results for predicted probabilities
  predictions <- tidybayes::spread_draws(samples,
                                         predicted_proba[herd_id],
                                         predicted_status[herd_id])


  ## tidying the results for model parameters
  n_tests <- length(grep("Se", colnames(samples[[1]])))
  herd_lev <- ifelse("pi_within" %in% colnames(samples[[1]]), 0, 1)

  if(herd_lev == 1 & n_tests == 1){

    parameters <- tidybayes::spread_draws(samples, Se, Sp, tau1, tau2)

  }

  if(herd_lev == 1 & n_tests > 1){

    parameters <- tidybayes::spread_draws(samples, Se[..], Sp[..], tau1, tau2)

  }

  if(herd_lev == 0 & n_tests == 1){

    parameters <- tidybayes::spread_draws(samples, Se, Sp, tau1, tau2, pi_within)

  }

  if(herd_lev == 0 & n_tests > 1){

    parameters <- tidybayes::spread_draws(samples, Se[..], Sp[..], tau1, tau2, pi_within)

  }

  list(
    parameters = parameters,
    predictions = predictions)

}

## Folder where models are saved
STOCfree_files <- function(out_path = out_path){

  out_path <- paste0("./", out_path)

  ## Does the folder already exists?
  ls_dirs <- list.dirs()

  if(!out_path %in% ls_dirs){

    dir.create(paste0(getwd(), out_path))

  }

  return(out_path)

}


#' Read output files for parameters generated by the STOC free model
#'
#' @param out_path folder where model outputs are saved. By default, a STOCfree_files folder is created in the working directory
#'
#' @return
#' @export
read_STOCfree_param <- function(out_path = "STOCfree_files"){

  nm <- paste0(out_path, "/parameters.csv")
  param <- read.csv(nm)

  return(param)

}


#' Read output files for predicted probabilities of infection generated by the STOC free model
#'
#' @param out_path folder where model outputs are saved. By default, a STOCfree_files folder is created in the working directory

#'
#' @return
#' @export
read_STOCfree_pred <- function(out_path = "STOCfree_files"){

  nm <- paste0(out_path, "/predictions.csv")
  pred <- read.csv(nm)

  return(pred)

}

